Feature/main window design
MossPiglets/Urania pull request #2
Opened 2021-08-24 17:47 UTC by Krystyna-Szybalska

2021-08-25 09:28 UTC, Morasiu commented
Usuń Avalonia :P

2021-08-25 17:52 UTC, Katarzyna-Kadziolka approved these changes

2021-08-29 13:08 UTC, Morasiu requested changes

2021-08-29 13:08 UTC, Morasiu commented on Urania/Urania.Deskop/App.axaml
> +		<FluentTheme Mode="Dark" />
Ten plik ciągle istnieje? Usuń cały projekt Urania.Deskop w VS, a potem ręcznie folder.

2021-08-29 19:08 UTC, Krystyna-Szybalska commented on Urania/Urania.Deskop/App.axaml
> +		<FluentTheme Mode="Dark" />
Ok, zapomniałam usunąć folderu najwyraźniej

2021-08-30 06:38 UTC, Morasiu approved these changes

2021-08-30 12:08 UTC, merged