Feature/o uranii logic
MossPiglets/Urania pull request #37
Opened 2021-09-28 10:57 UTC by Zofia-Szybalska

2021-09-28 11:31 UTC, Morasiu requested changes

2021-09-28 11:31 UTC, Morasiu commented on Urania/Urania.Desktop/MainWindow.xaml.cs
> +                Text = "Urania to aplikacja dedykowana twórcom zajmującym się techniką chainmaille, która pomoże Ci przeliczyć dowolne parametry posiadanych, bądź poszukiwanych ogniwek." +
Zapisz tekst w jakimś pliku i odczytuj go tutaj

2021-09-29 08:11 UTC, Katarzyna-Kadziolka commented on Urania/Urania.Desktop/MainWindow.xaml
> +                <RibbonMenuItem Header="O Uranii" Click="OUranii_Click"/>
Czepiam się, ale nazwałabym metodę AboutUrania_Click, żeby tak dziko poskiego w nazwę metody nie wrzucać

2021-09-29 08:12 UTC, Morasiu commented on Urania/Urania.Desktop/MainWindow.xaml
> +                <RibbonMenuItem Header="O Uranii" Click="OUranii_Click"/>
Nice. Popieram

2021-09-29 10:04 UTC, Morasiu requested changes

2021-09-29 10:04 UTC, Morasiu commented on Urania/Urania.Desktop/MainWindow.xaml.cs
> +            string _filePath = Directory.GetParent(Directory.GetParent(Directory.GetParent(Directory.GetCurrentDirectory()).FullName).FullName).FullName;
Okej. Na pewno musi być lepszy sposób. Może zapomniałaś oznaczyć pliku jako "Copy if newer" albo coś

2021-09-29 17:35 UTC, Katarzyna-Kadziolka approved these changes

2021-09-30 07:26 UTC, Morasiu approved these changes

2021-09-30 07:34 UTC, merged