Add BruxaPlOnClick
MossPiglets/Urania pull request #38
Opened 2021-09-29 17:32 UTC by Katarzyna-Kadziolka

2021-09-30 07:28 UTC, Morasiu requested changes

2021-09-30 07:28 UTC, Morasiu commented on Urania/Urania.Desktop/MainWindow.xaml
> +                <RibbonMenuItem Header="Otwórz Bruxa.pl" Click="BruxaPl_OnClick" />
`OpenBruxa_OnClick` <- zmień na coś takiego

2021-10-01 08:49 UTC, Zofia-Szybalska approved these changes

2021-10-01 09:24 UTC, Morasiu approved these changes

2021-10-01 10:46 UTC, merged