Feature/counting ar
MossPiglets/Urania pull request #4
Opened 2021-08-26 20:12 UTC by Katarzyna-Kadziolka

2021-08-26 20:28 UTC, Katarzyna-Kadziolka commented
Hmm teraz zauwważyłam, że nie uwzględniam nijak dzielenia przez zero. Wstawić jakiegoś ifa, czy mianownik nie ejst zerem i wyrzucać błąd, czy po prostu zostawić to programowi i tylko sprawdzić testami czy wyrzuca odpowiedni błąd?

2021-08-27 06:27 UTC, Morasiu requested changes

2021-08-27 06:27 UTC, Morasiu commented on Urania/Urania.Core/ArCalculator.cs
> +            if (wd?.GetType() == typeof(decimal) && od?.GetType() == typeof(decimal)) {
What? Czemu nie sprawdzasz czy id != null po prostu?

2021-08-27 06:29 UTC, Morasiu commented
Hmm... Chyba kod się tym zajmie

2021-08-27 06:36 UTC, Morasiu approved these changes

2021-08-27 06:36 UTC, Morasiu commented on Urania/Urania.Core/ArCalculator.cs
> +            throw new ArgumentException("More than one null argument");
Dobrze byłoby to zaprojektować tak, żeby były wiadomo, który argument jest null. No i lepiej użyć `ArgumentNullException`

2021-08-27 06:43 UTC, Katarzyna-Kadziolka commented on Urania/Urania.Core/ArCalculator.cs
> +            if (wd?.GetType() == typeof(decimal) && od?.GetType() == typeof(decimal)) {
późno było XD

2021-08-29 11:59 UTC, Katarzyna-Kadziolka commented on Urania/Urania.Core/ArCalculator.cs
> +            if (wd?.GetType() == typeof(decimal) && od?.GetType() == typeof(decimal)) {
poprawione :)

2021-08-29 12:00 UTC, Katarzyna-Kadziolka commented on Urania/Urania.Core/ArCalculator.cs
> +            throw new ArgumentException("More than one null argument");
Zmienione :)

2021-08-29 13:10 UTC, Morasiu requested changes

2021-08-29 13:10 UTC, Morasiu commented on Urania/Urania.Tests/ArCalculatorTests.cs
> +			Action act = () => ArCalculator.Calculate(null, null, od);
Czemu tu jest null null zamiast id, wd?

2021-08-29 13:10 UTC, Morasiu commented on Urania/Urania.Tests/ArCalculatorTests.cs
> +			Action act = () => ArCalculator.Calculate(id, null, null);
Tu też

2021-08-29 13:14 UTC, Katarzyna-Kadziolka commented on Urania/Urania.Tests/ArCalculatorTests.cs
> +			Action act = () => ArCalculator.Calculate(null, null, od);
zmienione

2021-08-29 13:14 UTC, Katarzyna-Kadziolka commented on Urania/Urania.Tests/ArCalculatorTests.cs
> +			Action act = () => ArCalculator.Calculate(id, null, null);
też zmienione :P

2021-08-29 13:20 UTC, Morasiu approved these changes

2021-08-31 08:21 UTC, Zofia-Szybalska approved these changes

2021-08-31 14:00 UTC, merged