WdCalculator
MossPiglets/Urania pull request #6
Opened 2021-08-31 08:23 UTC by Zofia-Szybalska

2021-08-31 12:02 UTC, Morasiu approved these changes

2021-08-31 13:09 UTC, Katarzyna-Kadziolka reviewed
Tylko klamerki popraw, żeby były jak w pliku WdCalculator

2021-08-31 15:50 UTC, Katarzyna-Kadziolka commented on Urania/Urania.Core/WdCalculator.cs
> +}
Brakuje mi walidacji czy nie wyjdzie nam ujemna liczba

2021-09-01 11:43 UTC, Krystyna-Szybalska reviewed
A co w sytuacji gdy ktoś wpisze ujemną wartość w któryś textbox? Czy to też nie powinno być obsłużone tutaj?

2021-09-01 14:42 UTC, Katarzyna-Kadziolka commented
Poza wyrzuceniem konkretnego błędu z konkretną informacją, nie możemy tutaj nic więcej zrobić

2021-09-01 15:54 UTC, Morasiu requested changes

2021-09-01 15:54 UTC, Morasiu commented on Urania/Urania.Core/WdCalculator.cs
> +                throw new ArgumentOutOfRangeException($"{nameof(id)} cannot be less than 0");
Prawidłowa implementacja tego wyjątku powinna wyglądać tak:
`throw new ArgumentOutOfRangeException(nameof(id), id, "Cannot be less than 0");`

2021-09-01 20:57 UTC, Katarzyna-Kadziolka approved these changes

2021-09-02 07:52 UTC, Morasiu requested changes

2021-09-02 07:52 UTC, Morasiu commented on Urania/Urania.Core/WdCalculator.cs
> +                    throw new ArgumentOutOfRangeException($"{nameof(od)} must be greater than {nameof(id)}");
Tutaj też jak wyżej implementacja ArgumentOutOfRangeException

2021-09-02 09:24 UTC, Morasiu requested changes

2021-09-02 09:24 UTC, Morasiu commented on Urania/Urania.Core/WdCalculator.cs
> +                    throw new ArgumentOutOfRangeException(nameof(ar), ar, $"must be greater than {nameof(id)}");
Usuń $ i z dużej litery i będzie git

2021-09-02 11:18 UTC, Morasiu approved these changes

2021-09-02 11:19 UTC, merged